baseURL = "https://tetzank.github.io/"
languageCode = "en-us"
title = "Dangerous Assembly"

disableLiveReload = true
disableHugoGeneratorInject = true

Paginate = 20

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
